### ISSUE TITLE
interceptOnChange example bugs

### ISSUE THREAD

**Issue by Gilstroem** [j0nas/light-form#11]
The input fields in the [interceptOnChange](http://light-form.surge.sh/interceptonchange) example don't allow deleting a character unless everything is selected, and adds two letters on every keypress

**Comment by j0nas** [comment]
That was meant as a simple example, but I can easily see how it didn't serve its purpose. I simplified that example and added descriptions for all examples in #12. Do you find the examples better explained and more focused now?

**Comment by Gilstroem** [comment]
Was the things I described intentional? If so, that was definitely not clear to me. New example works well, though. I enjoy using the library.
